apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-chaos-app
spec:
  podSelector:
    matchLabels:
      app: chaos-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: chaos-app
