apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: resilience-alerts
  labels:
    release: monitoring
spec:
  groups:
  - name: resilience.rules
    rules:

    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[5m])) > 0.8
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: High CPU Usage Detected

    - alert: HighMemoryUsage
      expr: sum(container_memory_usage_bytes) > 500000000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: High Memory Usage Detected

    - alert: PodDown
      expr: kube_pod_status_ready{condition="true"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Pod Not Ready
