apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2026-06-03T10:02:15Z"
  name: chaos-app
  namespace: default
  resourceVersion: "81577"
  uid: 6734f712-6af3-4229-99e2-77f37e16afdf
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chaos-app
status:
  conditions:
  - lastTransitionTime: "2026-06-03T10:02:30Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-06-03T10:02:30Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-06-03T10:07:31Z"
    message: the desired replica count is less than the minimum replica count
    reason: TooFewReplicas
    status: "True"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 2
        averageValue: 2m
      name: cpu
    type: Resource
  currentReplicas: 2
  desiredReplicas: 2
